application/controllers/Connection.php
=> [SC02] Add comment on connection file

application/controllers/Connection.php
=> [SC03] Remove Comment on Connection file

application/views/students/Student_info.php
=> [SC020]Correct Spelling in form

application/controllers/form.html, application/views/examples/welcome.php, application/views/students/Student_info.php
=> [SC027] correct code in form

application/views/students/Student_info.php
=> [SC011] Edite form student information

application/views/students/Student_info.php
=> [SC013] Fixed Image Background

application/views/students/Student_info.php
=> [SC011]correct text and update form

application/views/students/Student_info.php
=> [SC053] add some style to correct line

application/views/students/Student_info.php
=> [SC014] edite label

README.md
=> [Sc054] edit on readme.md file

application/controllers/c_student.php
=> [SC063]Create page coming soon

application/controllers/c_student.php, application/views/province.php
=> [SC064]create page coming soon

application/views/menu/index.php
=> [SC058] Change some error

application/views/province.php
=> [back]change background of coming soon page

application/views/students/Student_info.php
=> [SC071] Delete code on form student

application/views/candidates/can_list.php, application/views/candidates/new_candidate.php, application/views/candidates/view_can_detail.php, application/views/students/Student_info.php
This function can help to calculate automatically by getting the values from input into the total of expense.
=> [SC060] function calculate automatically in form expese

application/controllers/C_candidates.php, application/views/welcome.php
=> [SC073] add two more pie charts

application/controllers/Users.php, application/views/menu/index.php
=> [SC077] update profile form

application/config/config.php, application/controllers/C_candidates.php, application/models/Candidates_model.php, application/views/candidates/can_list.php, application/views/welcome.php
=> [SC075] list selected candidate from db by ajax

application/controllers/C_candidates.php, application/views/candidates/can_list.php
=> [SC064] Solve error

application/views/candidates/selectCandidate.php, application/views/students/Student_info.php
=> [SC071] auto calculate function family income

application/controllers/C_candidates.php, application/views/students/Student_info.php
=> [SC072] Change some errors

application/views/students/Student_info.php
=> [SC073] function caculate automatically in family expense

application/views/candidates/exportSelected.php
=> [SC071] Change number of ID in excel selected candidates

application/config/config.php, application/config/routes.php, application/controllers/C_candidates.php, application/controllers/Connection.php, application/models/Users_model.php
=> [SC085] Security on url after logout

application/controllers/C_candidates.php, application/models/Users_model.php, application/views/login/login.php
=> [SC085] Update form login and fix error on normal user

application/views/candidates/export.php
=> [SC072] Change Id in export to excel

application/controllers/C_candidates.php, application/views/candidates/can_list.php, application/views/candidates/new_candidate.php, application/views/menu/index.php, application/views/welcome.php
=> [SCN077] Update on add new candidate form

application/controllers/C_candidates.php, application/controllers/c_student.php, application/models/Candidates_model.php, application/views/candidates/new_candidate.php, application/views/welcome.php
=> [SC069] Update function add candidate

application/controllers/Users.php, application/models/Candidates_model.php, application/views/candidates/update_candidate.php
=> [SC074] send email when create new user

application/controllers/C_candidates.php, application/models/Candidates_model.php, application/views/candidates/new_candidate.php, application/views/candidates/update_candidate.php
=> [SC067c] try to make form update look good

application/views/candidates/new_candidate.php
=> [SC080] Update calculate and view function

application/controllers/C_candidates.php
=> [SC080] Solve error

application/controllers/C_candidates.php, application/views/candidates/can_list.php, application/views/welcome.php
=> [SC081] Change some information in pie chart and color of pie chart

application/views/candidates/can_list.php, application/views/welcome.php
=> [SC093]Update on province distribution

application/views/candidates/update_candidate.php
=> [SC090f] add option on select option

application/views/users/index.php
=> [SC089] reset password

application/views/candidates/new_candidate.php
=> [SC097]Update on add new candidate template

application/views/welcome.php
=> [SC099]Resolve conflict on welcome page

application/controllers/controller_backup/C_candidates.php, application/models/model_backup/Candidates_model.php, application/views/candidates/update_candidate.php
=> [SC0101]Update file on update
